version: "3"

services:
  mysql:
    container_name: ddd_forum_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${DDD_FORUM_DB_DEV_DB_NAME}
      - MYSQL_USER=${DDD_FORUM_DB_USER}
      - MYSQL_PASSWORD=${DDD_FORUM_DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  adminer:
    container_name: ddd_forum_adminer
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    restart: always

  redis:
    container_name: ddd_forum_redis
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  app:
    container_name: ddd_forum_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - 3000:3000
      - 5001:5001
    restart: always

volumes:
  mysql_data:
  redis_data:
